openapi: 3.1.0
info:
  title: ProblemDetails
  version: 1.0.0
  description: |
    The sole purpose of this API definition is to expose the `ProblemDetails` DTO.
  contact:
    url: 'https://github.com/patrickp-at-work/rfc7807-openapi/'
    name: patrickp-at-work
servers:
  - url: 'http://localhost'
paths: {}
components:
  schemas:
    ProblemDetails:
      title: ProblemDetails
      type: object
      properties:
        type:
          type: string
          description: |-
            A URI reference [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) that identifies the problem type.  

            This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028](https://datatracker.ietf.org/doc/html/rfc7807#ref-W3C.REC-html5-20141028)).

            When this member is not present, its value is assumed to be "about:blank".

            Consumers MUST use the "type" string as the primary identifier for the problem type.

            Accepts relative URIs.
        title:
          type: string
          description: |-
            A short, human-readable summary of the problem type.

            It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231, Section 3.4](https://datatracker.ietf.org/doc/html/rfc7231#section-3.4)).
        status:
          type: integer
          description: |-
            The HTTP status code ([RFC7231, Section 6](https://datatracker.ietf.org/doc/html/rfc7231#section-6)) generated by the origin server for this occurrence of the problem.

            This attribute, if present, is only advisory; it conveys the HTTP status code used for the convenience of the consumer.
        detail:
          type: string
          description: |-
            A human-readable explanation specific to this occurrence of the problem.

            If present, this ought to focus on _helping the client correct the problem_, rather than giving debugging information.

            Consumers SHOULD NOT parse the "detail" member for information.
        instance:
          type: string
          description: |-
            A URI reference that identifies the specific occurrence of the problem.

            It may or may not yield further information if dereferenced.

            Accepts relative URIs.
      description: 'An OpenAPI representation of the ProblemDetails object as specified by [RFC 7807, section 3](https://datatracker.ietf.org/doc/html/rfc7807#section-3).'
  securitySchemes: {}
